project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
website:
  title: "Dr. Leonardo Zanoli Capitani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

