project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
website:
  title: "Dr. Leonardo Zanoli Capitani"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/leomarameo7
      - icon: envelope
        href: mailto:leocapi07@gmail.com
  page-footer:    
    background: light
    left: This website is licensed under a [Creative Commons Attributions 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)

format:
  html:
    page-layout: full
    toc: false
    theme: 
     light: minty
     dark: solar
    css: styles.scss
editor: visual


