project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
website:
  title: "Dr. Leonardo Zanoli Capitani"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:    
    background: light
    left: This website is licensed under a [Creative Commons Attributions 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)

format:
  html:
    page-layout: full
    toc: false
    theme: 
      - styles.scss
    mainfont: Sen

editor: visual


