project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
website:
  title: "Dr. Leonardo Capitani"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: "Research Projects"
        href: scientific_projects/index_sci_pro.qmd
      - text: "Notebooks"
        href: notebooks/index_notebooks.qmd
      - icon: github
        href: https://github.com/leomarameo7
      - icon: envelope
        href: mailto:leocapi07@gmail.com
  sidebar:
    - title: "Notebooks"
      style: "docked"
      contents:
        - text: "Notebooks"
          href: notebooks/index_notebooks.qmd
        - text: "Clean data: lake Constance"
          href: notebooks/seewandell/CON_clean_dataset.html
        - text: "Gaussian Processes"
          href: notebooks/seewandell/GP_workbook.html
          
  page-footer:    
    background: light
    left: This website is licensed under a [Creative Commons Attributions 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)

format:
  html:
    page-layout: full
    toc: false
    theme: 
     light: default
     dark: slate
    light-dark: true
    css: styles.scss
editor: visual


