name: Render Quarto Website

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: r-lib/actions/setup-r@v2
      - uses: quarto-dev/quarto-actions@v2
        with:
          publish-dir: docs
